data_settings:
    dataset_path: 'dataset'
model:
    model_type: 'resnet' # resnet or efficentnet
    num_classes: 20
    checkpoint_folder: 'checkpoints'
fine_tuning:
    epochs: 10
    batch_size: 1
    learning_rate: 0.00001
train:
    epochs: 100
    batch_size: 8
    learning_rate: 0.001
